# Generated by Django 4.1.7 on 2023-05-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rack_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.rackgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.user')),
            ],
        ),
        migrations.CreateModel(
            name='OperationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_speed', models.FloatField()),
                ('weight', models.FloatField()),
                ('displacement', models.FloatField()),
                ('number_users', models.IntegerField()),
                ('is_hard_locked', models.BooleanField()),
                ('is_endpoint', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.rack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_light', models.BooleanField(null=True)),
                ('open_specific_rack', models.BooleanField(null=True)),
                ('ventilate', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.rack')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.user')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.rack')),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_obstructed', models.BooleanField(null=True)),
                ('is_skewed', models.BooleanField(null=True)),
                ('is_overload_motor', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.DateTimeField(null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racks.document')),
            ],
        ),
    ]
