# Generated by Django 4.1.7 on 2023-05-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['id', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('rack_name', 'rack_group')},
        ),
    ]
