# Generated by Django 4.1.7 on 2023-05-26 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0002_alter_rack_options_alter_rack_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='racks.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='racks.rack'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='racks.rack'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='racks.rackgroup'),
        ),
        migrations.AlterField(
            model_name='rackgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rackgroup',
            unique_together={('description', 'location')},
        ),
    ]
