# Generated by Django 4.1.7 on 2023-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0003_document_title_alter_borrowing_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
