# Generated by Django 4.1.7 on 2023-05-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0005_remove_borrowing_document_document_borrowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='borrowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowings', to='racks.borrowing'),
        ),
    ]
