# Generated by Django 4.1.7 on 2023-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0006_alter_document_borrowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='borrowing',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='document',
            field=models.ManyToManyField(to='racks.document'),
        ),
    ]
