# Generated by Django 4.1.7 on 2023-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0007_remove_document_borrowing_borrowing_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
