# Generated by Django 4.1.7 on 2023-05-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0008_alter_borrowing_date_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
