# Generated by Django 4.1.7 on 2023-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0009_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='breakdownstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='environmentstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operationstatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rackgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
