# Generated by Django 4.1.7 on 2023-05-29 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0010_borrowing_active_breakdownstatus_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
