# Generated by Django 4.1.7 on 2023-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0011_environmentstatus_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationstatus',
            name='weight',
        ),
        migrations.AddField(
            model_name='environmentstatus',
            name='smoke',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentstatus',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
