# Generated by Django 4.1.7 on 2023-05-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0012_remove_operationstatus_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationstatus',
            name='user',
        ),
    ]
