# Generated by Django 4.1.7 on 2023-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0014_breakdownstatus_updated_at_document_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='close_specific_rack',
            field=models.BooleanField(null=True),
        ),
    ]
