# Generated by Django 4.1.7 on 2023-07-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0015_operation_close_specific_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentstatus',
            name='rack',
        ),
        migrations.AddField(
            model_name='environmentstatus',
            name='rack_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
