# Generated by Django 4.1.7 on 2023-07-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0016_remove_environmentstatus_rack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdownstatus',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='operationstatus',
            name='rack',
        ),
        migrations.AddField(
            model_name='breakdownstatus',
            name='rack_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationstatus',
            name='rack_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
